spring.application.name=crowdfunding-backend

spring.datasource.url=jdbc:postgresql://ep-twilight-star-aqsm4ltl-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_lnBpN6VJ3XKc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Recommended for Neon
spring.datasource.hikari.maximum-pool-size=5

spring.security.user.name=
spring.security.user.password=

# USER JWT CONFIG
jwt.secret=mySuperSecureKeyThatIsAtLeast32BytesLong12345
jwt.expiration=3600000

# ADMIN JWT CONFIG
admin.jwt.secret=myAdminSuperSecureKeyThatIsAtLeast32BytesLong67890
admin.jwt.expiration=86400000

# Razorpay Config
razorpay.key=rzp_test_Sdl4QNf6TgnmWv
razorpay.secret=h30m46Iaj11TGQbVZSFh9Ktx

razorpay.webhook.secret=crowdfunding_webhook_secret_95181_01310