spring.application.name=crowdfunding-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/crowdfunding_db?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=
spring.security.user.password=

# USER JWT CONFIG
jwt.secret=mySuperSecureKeyThatIsAtLeast32BytesLong12345
jwt.expiration=3600000

# ADMIN JWT CONFIG
admin.jwt.secret=myAdminSuperSecureKeyThatIsAtLeast32BytesLong67890
admin.jwt.expiration=86400000

# Razorpay Config
razorpay.key=rzp_test_Sdl4QNf6TgnmWv
razorpay.secret=h30m46Iaj11TGQbVZSFh9Ktx

razorpay.webhook.secret=crowdfunding_webhook_secret_95181_01310